# Generated by Django 2.0.1 on 2018-01-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='field_type',
            new_name='file_type',
        ),
    ]
